# This workflow runs your Python script using a single version of Python.
# It is triggered on push/PR to main, manually, and on a 6-hour schedule.

name: Python Script Runner

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  # --- Debug Job (Optional, but kept for safety check) ---
  # This job ensures your secrets are correctly loaded into the environment.
  debug-secrets:
    runs-on: ubuntu-latest
    # Use the environment to ensure secrets are available
    environment: secrets 
    env:
      EMAIL: ${{ secrets.EMAIL }}
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
    steps:
      - name: Verify Secrets Loading
        run: |
          echo "EMAIL set? $([ -z \"$EMAIL\" ] && echo no || echo yes)"
          echo "APP_PASSWORD set? $([ -z \"$APP_PASSWORD\" ] && echo no || echo yes)"
          # Note: We avoid printing the actual values or lengths for security.

  # --- Main Build and Run Job ---
  run-script:
    # Renamed 'build' to 'run-script' for clarity
    runs-on: ubuntu-latest
    environment: secrets

    env:
      APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
      EMAIL: ${{ secrets.EMAIL }}

    steps:
    - name: Checkout code
      # Use the latest stable version
      uses: actions/checkout@v4 

    - name: Set up Python
      # Use the latest stable version (v4)
      uses: actions/setup-python@v4
      with:
        # Specify the exact version you need
        python-version: '3.10' 
        # Caching dependencies is highly recommended for speed
        cache: 'pip' 

    - name: Install dependencies
      # Simplified installation step. setup-python@v4 handles pip upgrade automatically.
      # It also correctly handles the requirements.txt file if it exists.
      run: |
        if [ -f requirements.txt ]; then 
          pip install -r requirements.txt
        else
          echo "No requirements.txt found. Skipping dependency installation."
        fi

    - name: Execute the Python script
      run: |
        python script.py